window.S3 = { buckets: [], busy: false, pageSize: 20, currentPage: 1, currentPrefix: "", objects: [], uploadLog: [], selectedEntries: [],
  async init() { if (!this._listening) { api.onS3Progress((p) => this.progress(p)); api.onS3TestProgress((p) => this.testProgress(p)); this._listening = true; } await this.load(); this.renameConfigButtons(); this.initDropZones(); },
  renameConfigButtons() { document.querySelectorAll('#s3-list button[onclick*="S3.edit"]').forEach((button) => { button.innerHTML='<i class="fas fa-sliders-h"></i> Config'; }); },
  async load() { const r = await api.s3GetBuckets(); this.buckets = r.buckets || []; const el = document.getElementById("s3-list"); if (!el) return; el.innerHTML = this.buckets.length ? this.buckets.map((b) => `<div class="card"><div class="card-hdr"><span class="card-title"><i class="fas fa-cloud" style="color:var(--accent)"></i> ${this.esc(b.name)}</span><span class="badge">${this.esc(b.bucket)}</span></div><div class="card-body"><div class="selectable" style="font-family:var(--mono);font-size:11px;color:var(--text2);margin-bottom:12px">${this.esc(b.endpoint)} / ${this.esc(b.prefix || "")}</div><div style="display:flex;gap:7px;flex-wrap:wrap"><button class="btn btn-primary btn-sm" onclick="S3.openBrowser('${b.id}')"><i class="fas fa-folder-open"></i> Browse / Sync</button><button class="btn btn-ghost btn-sm" onclick="S3.edit('${b.id}')"><i class="fas fa-edit"></i> Edit</button><button class="btn btn-ghost btn-sm" onclick="S3.test('${b.id}')"><i class="fas fa-plug"></i> Test</button><button class="btn btn-danger btn-sm" onclick="S3.remove('${b.id}')"><i class="fas fa-trash"></i></button></div></div></div>`).join("") : '<div class="empty-state"><i class="fas fa-cloud"></i><p>No S3 buckets configured.</p></div>'; },
  async openVault() {
    const status = await api.sftpVaultStatus();
    if (status.unlocked) return toast("Credential vault is already unlocked", "success");
    const returnPage = App.currentPage || "s3";
    await nav("sftp");
    await SFTP.openVault(async () => { await nav(returnPage); });
  },
  async newBucket() {
    const status = await api.sftpVaultStatus();
    if (!status.unlocked) {
      await nav("sftp");
      await SFTP.openVault(async () => { await nav("s3"); this._openBucketForm(); });
      return;
    }
    this._openBucketForm();
  },
  _openBucketForm() { ["id","name","endpoint","bucket","region","access","secret","prefix","local"].forEach((x) => { const e=document.getElementById("s3-"+x); if(e)e.value=""; }); document.getElementById("s3-region").value="us-east-1"; document.getElementById("s3-concurrency").value=4; openModal("m-s3"); },
  async edit(id) { const b=this.buckets.find(x=>x.id===id); if(!b)return; await this.newBucket(); document.getElementById("s3-id").value=b.id; ["name","endpoint","bucket","region","access","prefix","local"].forEach(x=>document.getElementById("s3-"+x).value=b[x === "access" ? "accessKey" : x] || ""); document.getElementById("s3-concurrency").value=b.concurrency||4; },
  async chooseFolder() { const p=await api.openFileDialog({properties:["openDirectory"]}); if(p)document.getElementById("s3-local").value=p; },
  async save() { const d={id:document.getElementById("s3-id").value,name:document.getElementById("s3-name").value,endpoint:document.getElementById("s3-endpoint").value,bucket:document.getElementById("s3-bucket").value,region:document.getElementById("s3-region").value,accessKey:document.getElementById("s3-access").value,secretKey:document.getElementById("s3-secret").value,prefix:document.getElementById("s3-prefix").value,localPath:document.getElementById("s3-local").value,concurrency:Number(document.getElementById("s3-concurrency").value)}; const r=await api.s3SaveBucket(d); if(!r.success)return toast(r.message,"error"); closeModal("m-s3"); await this.load(); toast("S3 bucket saved","success"); },
  async test(id) { const b=this.buckets.find(x=>x.id===id); this.showTestDialog(b); const r=await api.s3TestBucket(id); this.testResult=r; const close=document.getElementById("s3-test-close"); if(close)close.disabled=false; toast(r.success ? r.message : "S3 checks failed — see Debug Logs",r.success?"success":"error"); },
  showTestDialog(b) { document.getElementById("s3-test-dialog")?.remove(); const box=document.createElement("div");box.id="s3-test-dialog";box.className="s3-test-dialog";box.innerHTML=`<div class="s3-test-title"><i class="fas fa-plug"></i> S3 Connection Test</div><div class="s3-test-target">Endpoint: ${this.esc(b?.endpoint)}<br>Bucket: ${this.esc(b?.bucket)}<br>Region: ${this.esc(b?.region)} · Path-style: true</div><div id="s3-test-steps" class="s3-test-steps"></div><div class="s3-test-actions"><button class="btn btn-ghost btn-sm" onclick="nav('debug');S3.closeTestDialog()"><i class="fas fa-list"></i> Open Debug Logs</button><button id="s3-test-close" class="btn btn-primary btn-sm" disabled onclick="S3.closeTestDialog()">Close</button></div>`;document.body.appendChild(box); const steps=["HeadBucket","GetBucketLocation","ListObjectsV2","PutObject","GetObject","DeleteObject"];document.getElementById("s3-test-steps").innerHTML=steps.map((x,i)=>`<div id="s3-test-step-${i}" class="s3-test-step"><span class="s3-test-icon">${i+1}</span><span>${x}</span><span class="s3-test-state">Waiting</span></div>`).join(""); },
  testProgress(p) { const row=document.getElementById(`s3-test-step-${p.index}`);if(!row)return;row.classList.remove("running","success","error");row.classList.add(p.state);const state=row.querySelector(".s3-test-state");if(state)state.textContent=p.state==="running"?"Running…":p.state==="success"?`OK · HTTP ${p.status}`:`ERROR · HTTP ${p.status||"?"}`; },
  closeTestDialog() { document.getElementById("s3-test-dialog")?.remove(); },
  async openBrowser(id) { const status=await api.sftpVaultStatus(); if(!status.unlocked) { const returnPage=App.currentPage||"s3"; await nav("sftp"); await SFTP.openVault(async()=>{ await nav(returnPage); }); return; } if(!window.__s3Session) return api.s3OpenWindow(id); this.browserId=id; const b=this.buckets.find(x=>x.id===id); this.currentPrefix=b?.prefix||""; this.currentPage=1; this.uploadLog=[]; this.ensureProgressUi(); await this.refreshBrowser(); },
  ensureProgressUi() { const panel=document.querySelector(".s3-upload-panel"); if(!panel||document.getElementById("s3-transfer-progress"))return; const el=document.createElement("div"); el.id="s3-transfer-progress"; el.className="s3-transfer-progress"; el.innerHTML='<div class="s3-progress-head"><span id="s3-progress-label">Ready</span><span id="s3-progress-count">0 / 0</span></div><div class="s3-progress-track"><div id="s3-progress-bar"></div></div><div id="s3-progress-current" class="s3-progress-current"></div><button class="btn btn-danger btn-xs" onclick="api.s3Cancel();S3.progress({done:0,total:0,stopped:true})"><i class="fas fa-stop"></i> Stop</button>'; panel.insertBefore(el,document.getElementById("s3-upload-log")); },
  async refreshBrowser() { const el=document.getElementById("s3-object-list"); if(!el)return; el.innerHTML='<div class="empty-state"><i class="fas fa-spinner fa-spin"></i><p>Loading objects…</p></div>'; const r=await api.s3ListObjects(this.browserId,this.currentPrefix); if(!r.success)return el.innerHTML=`<div class="empty-state"><i class="fas fa-exclamation-triangle"></i><p>${this.esc(r.message)}</p></div>`; this.objects=r.items||[]; this.renderBrowser(); },
  renderBrowser() { const el=document.getElementById("s3-object-list"), prefix=this.currentPrefix||""; const folders=new Set(), files=[]; for(const o of this.objects){const rel=o.key.startsWith(prefix)?o.key.slice(prefix.length).replace(/^\//,""):o.key; const slash=rel.indexOf("/"); if(slash>0)folders.add(rel.slice(0,slash)); else if(rel)files.push({...o,display:rel});} const rows=[...folders].sort().map(f=>`<div class="s3-object-row s3-folder-row" onclick="S3.openFolder('${encodeURIComponent(f)}')" oncontextmenu="S3.showContext(event,'folder','${encodeURIComponent(f)}')"><i class="fas fa-folder" style="color:var(--yellow)"></i><span class="s3-object-key">${this.esc(f)}</span><span class="s3-object-size">Folder</span></div>`); const start=(this.currentPage-1)*this.pageSize, page=files.slice(start,start+this.pageSize); this.visibleObjects=page; rows.push(...page.map((o,i)=>`<div class="s3-object-row" oncontextmenu="S3.showContext(event,'file',${i})"><i class="fas fa-file" style="color:var(--accent)"></i><span class="s3-object-key" title="${this.esc(o.key)}">${this.esc(o.display)}</span><span class="s3-object-size">${fmtBytes(o.size)}</span><button class="btn btn-ghost btn-xs" onclick="event.stopPropagation();S3.downloadObject(${i})"><i class="fas fa-download"></i></button><button class="btn btn-ghost btn-xs" onclick="event.stopPropagation();S3.infoObject(${i})"><i class="fas fa-info-circle"></i></button><button class="btn btn-danger btn-xs" onclick="event.stopPropagation();S3.deleteObject(${i})"><i class="fas fa-trash"></i></button></div>`)); el.innerHTML=rows.join("")||'<div class="empty-state"><i class="fas fa-folder-open"></i><p>Folder is empty.</p></div>'; const total=Math.max(1,Math.ceil(files.length/this.pageSize)); const pager=files.length?`<button class="btn btn-ghost btn-xs" onclick="S3.changePage(-1)" ${this.currentPage<=1?"disabled":""}>Previous</button><span>Page ${this.currentPage} / ${total} · ${files.length} files</span><button class="btn btn-ghost btn-xs" onclick="S3.changePage(1)" ${this.currentPage>=total?"disabled":""}>Next</button>`:""; let top=document.getElementById("s3-pagination-top"); if(!top){top=document.createElement("div");top.id="s3-pagination-top";top.className="s3-pagination s3-pagination-top";el.parentNode.insertBefore(top,el);} top.innerHTML=pager; document.getElementById("s3-pagination").innerHTML=pager; document.getElementById("s3-breadcrumb").textContent=prefix||"/"; },
  openFolder(name) { this.currentPrefix=(this.currentPrefix?this.currentPrefix.replace(/\/+$/,"/"):"")+decodeURIComponent(name)+"/"; this.currentPage=1; this.refreshBrowser(); }, goParent() { const p=this.currentPrefix.replace(/\/+$/,""), i=p.lastIndexOf("/"); this.currentPrefix=i>=0?p.slice(0,i+1):""; this.currentPage=1; this.refreshBrowser(); }, changePage(delta) { this.currentPage=Math.max(1,this.currentPage+delta); this.renderBrowser(); }, setPageSize(value) { this.pageSize=Math.max(1,Math.min(100,Number(value)||20)); this.currentPage=1; this.renderBrowser(); }, addPageSizeSelector(parent) { if(!parent||!parent.innerHTML)return; const select=document.createElement("select"); select.className="fi s3-page-size"; select.innerHTML=[20,50,100].map((n)=>`<option value="${n}" ${n===this.pageSize?"selected":""}>${n}/page</option>`).join(""); select.onchange=()=>this.setPageSize(select.value); parent.appendChild(select); },
  showContext(event, kind, value) { event.preventDefault(); event.stopPropagation(); this.hideContext(); const menu=document.createElement("div"); menu.id="s3-context-menu"; menu.className="ctx-menu"; const add=(icon,label,fn,danger=false)=>{const item=document.createElement("div");item.className=`ctx-item${danger?" ctx-danger":""}`;item.innerHTML=`<i class="fas ${icon}"></i> ${label}`;item.onclick=()=>{this.hideContext();fn();};menu.appendChild(item);}; if(kind==="folder"){const name=decodeURIComponent(value),prefix=(this.currentPrefix||"")+name+"/";add("fa-folder-open","Open",()=>this.openFolder(value));add("fa-download","Download folder",()=>this.downloadPrefix(prefix));add("fa-trash","Delete folder",()=>this.deletePrefix(prefix),true);}else{const i=Number(value);add("fa-download","Download",()=>this.downloadObject(i));add("fa-info-circle","Properties",()=>this.infoObject(i));add("fa-trash","Delete",()=>this.deleteObject(i),true);} document.body.appendChild(menu); menu.style.left=`${Math.min(event.clientX,window.innerWidth-menu.offsetWidth-8)}px`;menu.style.top=`${Math.min(event.clientY,window.innerHeight-menu.offsetHeight-8)}px`;setTimeout(()=>document.addEventListener("click",()=>this.hideContext(),{once:true}),0); },
  showUploadContext(event) { event.preventDefault(); event.stopPropagation(); this.hideContext(); const menu=document.createElement("div");menu.id="s3-context-menu";menu.className="ctx-menu";const item=document.createElement("div");item.className="ctx-item";item.innerHTML='<i class="fas fa-upload"></i> Upload File';item.onmousedown=(e)=>e.stopPropagation();item.onclick=()=>{this.hideContext();this.uploadFiles();};menu.appendChild(item);document.body.appendChild(menu);menu.style.left=`${event.clientX}px`;menu.style.top=`${event.clientY}px`;setTimeout(()=>document.addEventListener("click",()=>this.hideContext(),{once:true}),0); },
  hideContext() { document.getElementById("s3-context-menu")?.remove(); },
  async downloadPrefix(prefix) { const p=await api.openFileDialog({properties:["openDirectory"]}); if(!p)return; const b=this.buckets.find(x=>x.id===this.browserId); this.activeOperation="Download"; this.progress({done:0,total:0}); const r=await api.s3DownloadPrefix(this.browserId,prefix,p,{concurrency:b?.concurrency}); this.activeOperation=""; toast(r.success?`Downloaded ${r.count||0} files`:"Download folder failed",r.success?"success":"error"); },
  async deletePrefix(prefix) { if(prompt(`This permanently deletes all objects in ${prefix}. Type DELETE to confirm:`)!=="DELETE")return; const items=this.objects.filter(o=>o.key.startsWith(prefix)); const results=await Promise.all(items.map(o=>api.s3DeleteObject(this.browserId,o.key))); if(results.some(r=>!r.success))toast("Some objects could not be deleted","error"); await this.refreshBrowser(); },
  async uploadFiles() { const p=await api.openFileDialog({properties:["openFile","openDirectory","multiSelections"]}); if(p?.length) await this.uploadPaths(p); },
  async uploadFolder() { const p=await api.openFileDialog({properties:["openDirectory","multiSelections"]}); if(p?.length) await this.uploadPaths(p); },
  async dropUpload(event, zone) {
    event.preventDefault();
    event.stopPropagation();
    zone.classList.remove("drag-over");
    const paths = [];
    const seen = new Set();
    const add = (file) => {
      if (!file) return;
      let path = "";
      try {
        if (typeof api.getPathForFile === "function") path = api.getPathForFile(file) || "";
      } catch (_) {}
      if (!path) path = file.path || "";
      path = String(path).trim();
      if (!path || seen.has(path)) return;
      seen.add(path);
      paths.push(path);
    };
    const dt = event.dataTransfer;
    if (dt?.items?.length) {
      for (let i = 0; i < dt.items.length; i++) {
        const item = dt.items[i];
        if (item?.kind === "file") add(item.getAsFile());
      }
    }
    if (!paths.length && dt?.files?.length) {
      for (let i = 0; i < dt.files.length; i++) add(dt.files[i]);
    }
    if (!paths.length) return toast("Could not read dropped files. Try again or use Upload.", "warn");
    await this.uploadPaths(paths);
  },
  _bindS3DropZone(zone) {
    if (!zone || zone.dataset.s3DropBound === "1") return;
    zone.dataset.s3DropBound = "1";
    const stillInside = (e) => {
      const related = e.relatedTarget;
      if (related && zone.contains(related)) return true;
      const under = document.elementFromPoint(e.clientX, e.clientY);
      return !!(under && zone.contains(under));
    };
    zone.addEventListener("dragenter", (e) => {
      if (!e.dataTransfer?.types?.includes("Files")) return;
      e.preventDefault();
      zone.classList.add("drag-over");
    });
    zone.addEventListener("dragover", (e) => {
      if (!e.dataTransfer?.types?.includes("Files")) return;
      e.preventDefault();
      if (e.dataTransfer) e.dataTransfer.dropEffect = "copy";
      zone.classList.add("drag-over");
    });
    zone.addEventListener("dragleave", (e) => {
      if (stillInside(e)) return;
      zone.classList.remove("drag-over");
    });
    zone.addEventListener("drop", (e) => this.dropUpload(e, zone));
  },
  initDropZones() {
    // Bind the widest targets only — nested .s3-drop-zone is covered by the panel.
    const zones = [
      document.querySelector(".s3-upload-panel"),
      document.getElementById("s3-object-list"),
      document.querySelector(".s3-drop-zone"),
    ].filter(Boolean);
    const seen = new Set();
    for (const zone of zones) {
      if (seen.has(zone)) continue;
      // Skip the dashed box when its parent panel is already a drop target.
      if (zone.classList.contains("s3-drop-zone") && zone.closest(".s3-upload-panel") && seen.has(zone.closest(".s3-upload-panel"))) {
        continue;
      }
      seen.add(zone);
      this._bindS3DropZone(zone);
    }
  },
  async uploadPaths(items) { const b=this.buckets.find(x=>x.id===this.browserId); this.activeOperation="Upload"; this.progress({done:0,total:0}); try { const r=await api.s3UploadPaths(this.browserId,items,{concurrency:b?.concurrency}); this.uploadLog.unshift(`${new Date().toLocaleTimeString()}  Uploaded ${r.count||0} files`); this.renderUploadLog(); toast(`Uploaded ${r.count||0} files`,"success"); await this.refreshBrowser(); } catch(e) { this.uploadLog.unshift(`${new Date().toLocaleTimeString()}  ERROR: ${e.message}`); this.renderUploadLog(); toast(e.message,"error"); } finally { this.activeOperation=""; } },
  renderUploadLog() { const el=document.getElementById("s3-upload-log"); if(el)el.innerHTML=this.uploadLog.slice(0,30).map(x=>`<div>${this.esc(x)}</div>`).join(""); },
  async downloadObject(i) { const o=this.visibleObjects[i]; const p=await api.openFileDialog({properties:["openDirectory"]}); if(!p)return; const r=await api.s3DownloadObject(this.browserId,o.key,`${p}/${o.key.split("/").pop()}`); toast(r.success?"Downloaded":"Download failed",r.success?"success":"error"); },
  async deleteObject(i) { const o=this.visibleObjects[i]; if(prompt(`This permanently deletes ${o.key}. Type DELETE to confirm:`)!=="DELETE")return; const r=await api.s3DeleteObject(this.browserId,o.key); if(!r.success)return toast(r.message,"error"); await this.refreshBrowser(); },
  infoObject(i) { const o=this.visibleObjects[i]; alert(`Key: ${o.key}\nSize: ${fmtBytes(o.size)}\nPrefix: ${this.currentPrefix||"/"}`); },
  async remove(id) { if(!confirm("Delete this S3 configuration?"))return; await api.s3DeleteBucket(id); await this.load(); },
  async run(id,direction) { if(this.busy)return toast("A sync is already running","warn"); const b=this.buckets.find(x=>x.id===id); if(!b)return; this.busy=true; this.activeOperation=direction === "up" ? "Upload" : "Download"; this.progress({done:0,total:0}); const opts={localPath:b.localPath,concurrency:b.concurrency}; toast(direction === "up" ? "Sync Up started" : "Sync Down started","info"); try { const r=direction === "up" ? await api.s3Upload(id,opts) : await api.s3Download(id,opts); toast(`${direction === "up" ? "Uploaded" : "Downloaded"} ${r.count||0} files`,"success"); } catch(e) { toast(e.message||"S3 sync failed","error"); } this.activeOperation=""; this.busy=false; },
  async downloadObject(i) { const o=this.visibleObjects[i]; if(!o)return; const p=await api.openFileDialog({properties:["openDirectory"]}); if(!p)return; this.ensureProgressUi(); this.activeOperation="Download"; this.progress({done:0,total:1,item:o.key}); try { const r=await api.s3DownloadObject(this.browserId,o.key,`${p}/${o.key.split("/").pop()}`); if(!r.success)throw new Error(r.message||"Download failed"); this.progress({done:1,total:1,item:o.key}); this.uploadLog.unshift(`${new Date().toLocaleTimeString()}  Downloaded: ${o.key}`); this.renderUploadLog(); toast(`Downloaded: ${o.key}`,"success"); } catch(e) { this.progress({done:0,total:1,item:o.key,stopped:true}); this.uploadLog.unshift(`${new Date().toLocaleTimeString()}  Download error: ${o.key} — ${e.message}`); this.renderUploadLog(); toast(`Download failed: ${e.message}`,"error"); } finally { this.activeOperation=""; } },
  async downloadPrefix(prefix) { const p=await api.openFileDialog({properties:["openDirectory"]}); if(!p)return; const b=this.buckets.find(x=>x.id===this.browserId); this.ensureProgressUi(); this.activeOperation="Download"; this.progress({done:0,total:0,item:prefix}); try { const r=await api.s3DownloadPrefix(this.browserId,prefix,p,{concurrency:b?.concurrency}); if(!r.success)throw new Error(r.message||"Download folder failed"); this.uploadLog.unshift(`${new Date().toLocaleTimeString()}  Downloaded folder: ${prefix} (${r.count||0} files)`); this.renderUploadLog(); toast(`Downloaded folder: ${prefix} (${r.count||0} files)`,"success"); } catch(e) { this.progress({done:0,total:0,item:prefix,stopped:true}); this.uploadLog.unshift(`${new Date().toLocaleTimeString()}  Folder download error: ${prefix} — ${e.message}`); this.renderUploadLog(); toast(`Folder download failed: ${e.message}`,"error"); } finally { this.activeOperation=""; } },
  showContext(event, kind, value) { event.preventDefault(); event.stopPropagation(); this.hideContext(); const menu=document.createElement("div"); menu.id="s3-context-menu"; menu.className="ctx-menu"; const name=kind==="folder"?decodeURIComponent(value):(this.visibleObjects[Number(value)]?.display||""); const heading=document.createElement("div"); heading.className="ctx-section"; heading.innerHTML=`<i class="fas ${kind==="folder"?"fa-folder":"fa-file"}"></i> ${kind==="folder"?"FOLDER":"FILE"}: ${this.esc(name)}`; menu.appendChild(heading); const add=(icon,label,fn,danger=false)=>{const item=document.createElement("div");item.className=`ctx-item${danger?" ctx-danger":""}`;item.innerHTML=`<i class="fas ${icon}"></i> ${label}`;item.onmousedown=(e)=>e.stopPropagation();item.onclick=(e)=>{e.stopPropagation();this.hideContext();fn();};menu.appendChild(item);}; if(kind==="folder"){const prefix=(this.currentPrefix||"")+name+"/";add("fa-folder-open","Open folder",()=>this.openFolder(value));add("fa-download","Download folder",()=>this.downloadPrefix(prefix));add("fa-trash","Delete folder",()=>this.deletePrefix(prefix),true);}else{const i=Number(value);add("fa-download","Download file",()=>this.downloadObject(i));add("fa-info-circle","Properties",()=>this.infoObject(i));add("fa-trash","Delete file",()=>this.deleteObject(i),true);} document.body.appendChild(menu); menu.style.left=`${Math.min(event.clientX,window.innerWidth-menu.offsetWidth-8)}px`;menu.style.top=`${Math.min(event.clientY,window.innerHeight-menu.offsetHeight-8)}px`;setTimeout(()=>document.addEventListener("click",()=>this.hideContext(),{once:true}),0); },
  async deleteObject(i) { const o=this.visibleObjects[i]; if(!o)return; if(prompt(`This permanently deletes FILE:\n${o.key}\nType DELETE to confirm:`)!=="DELETE")return; this.uploadLog.unshift(`${new Date().toLocaleTimeString()}  Deleting file: ${o.key}`); this.renderUploadLog(); toast(`Deleting file: ${o.key}`,"info"); try { const r=await api.s3DeleteObject(this.browserId,o.key); if(!r.success)throw new Error(r.message||"Delete failed"); this.uploadLog.unshift(`${new Date().toLocaleTimeString()}  Deleted file: ${o.key}`); this.renderUploadLog(); toast(`Deleted file: ${o.key}`,"success"); await this.refreshBrowser(); } catch(e) { this.uploadLog.unshift(`${new Date().toLocaleTimeString()}  Delete error: ${o.key} — ${e.message}`); this.renderUploadLog(); toast(`Delete failed: ${e.message}`,"error"); } },
  async askDelete(kind, name) { return new Promise((resolve) => { document.getElementById("s3-delete-confirm")?.remove(); const box=document.createElement("div"); box.id="s3-delete-confirm"; box.className="s3-confirm-backdrop"; box.innerHTML=`<div class="s3-confirm-box"><h3><i class="fas fa-triangle-exclamation"></i> Delete ${kind}</h3><p>This action cannot be recovered.</p><div class="s3-confirm-name">${this.esc(name)}</div><label>Type <strong>DELETE</strong> to confirm</label><input id="s3-delete-input" class="fi" autocomplete="off" spellcheck="false"><div class="s3-confirm-actions"><button class="btn btn-ghost" id="s3-delete-cancel">Cancel</button><button class="btn btn-danger" id="s3-delete-submit" disabled>Delete permanently</button></div></div>`; document.body.appendChild(box); const input=box.querySelector("#s3-delete-input"), submit=box.querySelector("#s3-delete-submit"); const finish=(ok)=>{box.remove();resolve(ok);}; input.addEventListener("input",()=>{submit.disabled=input.value!=="DELETE";}); box.querySelector("#s3-delete-cancel").onclick=()=>finish(false); submit.onclick=()=>finish(true); input.focus(); }); },
  async deleteObject(i) { const o=this.visibleObjects[i]; if(!o)return; if(!(await this.askDelete("FILE",o.key)))return; this.uploadLog.unshift(`${new Date().toLocaleTimeString()}  Deleting file: ${o.key}`); this.renderUploadLog(); toast(`Deleting file: ${o.key}`,"info"); try { const r=await api.s3DeleteObject(this.browserId,o.key); if(!r.success)throw new Error(r.message||"Delete failed"); this.uploadLog.unshift(`${new Date().toLocaleTimeString()}  Deleted file: ${o.key}`); this.renderUploadLog(); toast(`Deleted file: ${o.key}`,"success"); await this.refreshBrowser(); } catch(e) { this.uploadLog.unshift(`${new Date().toLocaleTimeString()}  Delete error: ${o.key} — ${e.message}`); this.renderUploadLog(); toast(`Delete failed: ${e.message}`,"error"); } },
  async deletePrefix(prefix) { if(!(await this.askDelete("FOLDER",prefix)))return; const items=this.objects.filter(o=>o.key.startsWith(prefix)); if(!items.length)return toast(`Folder is empty: ${prefix}`,"warn"); this.uploadLog.unshift(`${new Date().toLocaleTimeString()}  Deleting folder: ${prefix} (${items.length} files)`); this.renderUploadLog(); toast(`Deleting folder: ${prefix}`,"info"); try { const results=await Promise.all(items.map(o=>api.s3DeleteObject(this.browserId,o.key))); const failed=results.filter(r=>!r.success); if(failed.length)throw new Error(`${failed.length} file(s) could not be deleted`); this.uploadLog.unshift(`${new Date().toLocaleTimeString()}  Deleted folder: ${prefix} (${items.length} files)`); this.renderUploadLog(); toast(`Deleted folder: ${prefix}`,"success"); await this.refreshBrowser(); } catch(e) { this.uploadLog.unshift(`${new Date().toLocaleTimeString()}  Folder delete error: ${prefix} — ${e.message}`); this.renderUploadLog(); toast(`Folder delete failed: ${e.message}`,"error"); } },
  ensureProgressUi() { const panel=document.querySelector(".s3-upload-panel"); if(!panel)return; if(!document.getElementById("s3-transfer-progress")){const el=document.createElement("div");el.id="s3-transfer-progress";el.className="s3-transfer-progress";el.innerHTML='<div class="s3-progress-head"><span id="s3-progress-label">Ready</span><span id="s3-progress-count">0 / 0</span></div><div class="s3-progress-track"><div id="s3-progress-bar"></div></div><div id="s3-progress-current" class="s3-progress-current"></div><button class="btn btn-danger btn-xs" onclick="api.s3Cancel();S3.progress({done:0,total:0,stopped:true})"><i class="fas fa-stop"></i> Stop</button>';panel.insertBefore(el,document.getElementById("s3-upload-log"));} if(!document.getElementById("s3-transfer-float")){const el=document.createElement("div");el.id="s3-transfer-float";el.className="s3-transfer-float";el.innerHTML='<div class="s3-progress-head"><strong id="s3-float-label">Ready</strong><span id="s3-float-count">0 / 0</span></div><div class="s3-progress-track"><div id="s3-float-bar"></div></div><div id="s3-float-current" class="s3-progress-current"></div>';document.body.appendChild(el);} },
  progress(p) { const bar=document.getElementById("s3-progress-bar"), label=document.getElementById("s3-progress-label"), count=document.getElementById("s3-progress-count"), current=document.getElementById("s3-progress-current"), fbar=document.getElementById("s3-float-bar"), flabel=document.getElementById("s3-float-label"), fcount=document.getElementById("s3-float-count"), fcurrent=document.getElementById("s3-float-current"); if(!bar&&!fbar)return; const total=Number(p?.total)||0, done=Number(p?.done)||0, pct=total?Math.round(done/total*100):0, status=p?.stopped?"Stopped / Failed":(this.activeOperation?`${this.activeOperation} in progress`:(total?"Transferring":"Ready")), item=p?.item?String(p.item):""; if(bar){bar.style.width=`${pct}%`;label.textContent=status;count.textContent=`${done} / ${total}`;current.textContent=item;} if(fbar){fbar.style.width=`${pct}%`;flabel.textContent=status;fcount.textContent=`${done} / ${total}`;fcurrent.textContent=item;} if(total)document.title=`S3 ${this.activeOperation||"Transfer"} ${done}/${total}`; },
  esc(v) { return String(v||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c])); }
};

// S3 multi-selection and combined folder/file pagination.
const _s3UploadPaths = S3.uploadPaths;
S3.uploadPaths = async function(items) { this.uploadLog.unshift(`${new Date().toLocaleTimeString()}  Upload started: ${items.length} selected item(s)`); this.renderUploadLog(); const result=await _s3UploadPaths.call(this,items); if(result?.success){this.progress({done:result.count||0,total:result.count||0,item:`Upload completed: ${result.count||0} file(s)`,completed:true});this.uploadLog.unshift(`${new Date().toLocaleTimeString()}  Upload completed: ${result.count||0} file(s)`);this.renderUploadLog();} return result; };
const _s3DownloadPrefix = S3.downloadPrefix;
S3.downloadPrefix = async function(prefix) { const result=await _s3DownloadPrefix.call(this,prefix); if(result?.success){this.progress({done:result.count||0,total:result.count||0,item:`Download completed: ${prefix}`,completed:true});} return result; };
S3.renderBrowser = function() {
  const el=document.getElementById("s3-object-list"), prefix=this.currentPrefix||"", folders=new Set(), files=[];
  for(const o of this.objects){const rel=o.key.startsWith(prefix)?o.key.slice(prefix.length).replace(/^\//,""):o.key;const slash=rel.indexOf("/");if(slash>0)folders.add(rel.slice(0,slash));else if(rel)files.push({...o,display:rel});}
  const entries=[...folders].sort().map(name=>({kind:"folder",name,key:`${prefix}${name}/`})).concat(files.sort((a,b)=>a.display.localeCompare(b.display)).map(o=>({kind:"file",name:o.display,key:o.key,obj:o})));
  const pages=Math.max(1,Math.ceil(entries.length/this.pageSize));this.currentPage=Math.min(this.currentPage,pages);const page=entries.slice((this.currentPage-1)*this.pageSize,this.currentPage*this.pageSize);this.visibleObjects=page.filter(x=>x.kind==="file").map(x=>x.obj);const isChecked=e=>this.selectedEntries.some(x=>x.kind===e.kind&&x.key===e.key)?"checked":"";
  el.innerHTML=page.map(e=>e.kind==="folder"?`<div class="s3-object-row s3-folder-row" onclick="S3.openFolder('${encodeURIComponent(e.name)}')" oncontextmenu="S3.showContext(event,'folder','${encodeURIComponent(e.name)}')"><input type="checkbox" ${isChecked(e)} onclick="event.stopPropagation()" onchange="S3.toggleSelection('folder','${this.esc(e.key)}','${this.esc(e.name)}',this.checked)"><i class="fas fa-folder" style="color:var(--yellow)"></i><span class="s3-object-key">${this.esc(e.name)}</span><span class="s3-object-size">Folder</span></div>`:`<div class="s3-object-row" oncontextmenu="S3.showContext(event,'file',${this.visibleObjects.indexOf(e.obj)})"><input type="checkbox" ${isChecked(e)} onclick="event.stopPropagation()" onchange="S3.toggleSelection('file','${this.esc(e.key)}','${this.esc(e.name)}',this.checked)"><i class="fas fa-file" style="color:var(--accent)"></i><span class="s3-object-key" title="${this.esc(e.key)}">${this.esc(e.name)}</span><span class="s3-object-size">${fmtBytes(e.obj.size)}</span><button class="btn btn-ghost btn-xs" onclick="event.stopPropagation();S3.downloadObject(${this.visibleObjects.indexOf(e.obj)})"><i class="fas fa-download"></i></button><button class="btn btn-ghost btn-xs" onclick="event.stopPropagation();S3.infoObject(${this.visibleObjects.indexOf(e.obj)})"><i class="fas fa-info-circle"></i></button><button class="btn btn-danger btn-xs" onclick="event.stopPropagation();S3.deleteObject(${this.visibleObjects.indexOf(e.obj)})"><i class="fas fa-trash"></i></button></div>`).join("")||'<div class="empty-state"><i class="fas fa-folder-open"></i><p>Folder is empty.</p></div>';
  let actions=document.getElementById("s3-selection-actions");if(!actions){actions=document.createElement("div");actions.id="s3-selection-actions";actions.className="s3-selection-actions";el.parentNode.insertBefore(actions,el);}actions.innerHTML=this.selectedEntries.length?`<span>${this.selectedEntries.length} selected</span><button class="btn btn-ghost btn-xs" onclick="S3.downloadSelected()"><i class="fas fa-download"></i> Download selected</button><button class="btn btn-danger btn-xs" onclick="S3.deleteSelected()"><i class="fas fa-trash"></i> Delete selected</button>`:"";
  const pager=entries.length?`<button class="btn btn-ghost btn-xs" onclick="S3.changePage(-1)" ${this.currentPage<=1?"disabled":""}>Previous</button><span>Page ${this.currentPage} / ${pages} · ${entries.length} items</span><button class="btn btn-ghost btn-xs" onclick="S3.changePage(1)" ${this.currentPage>=pages?"disabled":""}>Next</button>`:"";let top=document.getElementById("s3-pagination-top");if(!top){top=document.createElement("div");top.id="s3-pagination-top";top.className="s3-pagination s3-pagination-top";el.parentNode.insertBefore(top,el);}top.innerHTML=pager;document.getElementById("s3-pagination").innerHTML=pager;document.getElementById("s3-breadcrumb").textContent=prefix||"/";
};
S3.toggleSelection=function(kind,key,name,selected){this.selectedEntries=this.selectedEntries.filter(x=>!(x.kind===kind&&x.key===key));if(selected)this.selectedEntries.push({kind,key,name});this.renderBrowser();};
S3.downloadSelected=async function(){const entries=[...this.selectedEntries];if(!entries.length)return;const p=await api.openFileDialog({properties:["openDirectory"]});if(!p)return;this.ensureProgressUi();this.activeOperation="Download";const errors=[];for(let i=0;i<entries.length;i++){const e=entries[i];try{const r=e.kind==="folder"?await api.s3DownloadPrefix(this.browserId,e.key,p,{concurrency:this.buckets.find(x=>x.id===this.browserId)?.concurrency}):await api.s3DownloadObject(this.browserId,e.key,`${p}/${e.key.split("/").pop()}`);if(!r.success)throw new Error(r.message||"Download failed");this.progress({done:i+1,total:entries.length,item:`${e.kind}: ${e.name}`});}catch(err){errors.push(`${e.name}: ${err.message}`);}}this.uploadLog.unshift(`${new Date().toLocaleTimeString()}  ${errors.length?"Download completed with errors":"Downloaded selected items"}`);this.renderUploadLog();toast(errors.length?`Download has ${errors.length} error(s)`:"Selected items downloaded",errors.length?"error":"success");this.activeOperation="";};
S3.deleteSelected=async function(){const entries=[...this.selectedEntries];if(!entries.length||!(await this.askDelete("SELECTED ITEMS",entries.map(x=>x.name).join(", "))))return;const keys=new Set();for(const e of entries){if(e.kind==="folder")this.objects.filter(o=>o.key.startsWith(e.key)).forEach(o=>keys.add(o.key));else keys.add(e.key);}toast(`Deleting ${keys.size} object(s)…`,"info");try{const results=await Promise.all([...keys].map(key=>api.s3DeleteObject(this.browserId,key)));const failed=results.filter(r=>!r.success);if(failed.length)throw new Error(`${failed.length} object(s) could not be deleted`);toast(`Deleted ${keys.size} object(s)`,"success");this.selectedEntries=[];await this.refreshBrowser();}catch(e){toast(`Delete failed: ${e.message}`,"error");}};
const _s3DeleteSelected = S3.deleteSelected;
S3.deleteSelected = async function() { const count=this.selectedEntries.length; this.uploadLog.unshift(`${new Date().toLocaleTimeString()}  Delete selected started: ${count} item(s)`); this.renderUploadLog(); await _s3DeleteSelected.call(this); this.uploadLog.unshift(`${new Date().toLocaleTimeString()}  Delete selected finished`); this.renderUploadLog(); };
