const fs = require("fs-extra");
const path = require("path");
const https = require("https");
const http = require("http");
const crypto = require("crypto");
const sftp = require("./sftp");
const log = require("./logger");

let cancelled = false;
const filePath = () => path.join(global.CONST.DATA_DIR, "remote-connections", "s3-buckets.json");
const sha256 = (v) => crypto.createHash("sha256").update(v).digest("hex");
const hmac = (key, value) => crypto.createHmac("sha256", key).update(value).digest();
const encodePath = (v) => String(v || "").split("/").map((part) => encodeURIComponent(part).replace(/[!'()*]/g, (c) => `%${c.charCodeAt(0).toString(16).toUpperCase()}`)).join("/");
const encodeQuery = (v) => encodeURIComponent(String(v)).replace(/[!'()*]/g, (c) => `%${c.charCodeAt(0).toString(16).toUpperCase()}`);

async function readAll() { try { return await fs.readJson(filePath()); } catch { return []; } }
async function writeAll(items) { await fs.ensureDir(path.dirname(filePath()), { mode: 0o700 }); await fs.writeJson(filePath(), items, { spaces: 2, mode: 0o600 }); await fs.chmod(filePath(), 0o600).catch(() => {}); }
function publicConfig(c) { return { ...c, secretKey: c.secretKey ? "••••••••" : "", hasSecretKey: !!c.secretKey, accessKey: c.accessKey || "" }; }
async function getBuckets() { return { success: true, buckets: (await readAll()).map(publicConfig) }; }
async function saveBucket(data) {
  if (!data.name || !data.bucket || !data.endpoint || !data.region || !data.accessKey) return { success: false, message: "Name, endpoint, region, bucket and access key are required" };
  const all = await readAll(); const index = all.findIndex((x) => x.id === data.id);
  if (!data.secretKey && index < 0) return { success: false, message: "Secret key is required" };
  const item = { id: data.id || Date.now().toString(36), name: data.name, endpoint: data.endpoint.replace(/\/$/, ""), region: data.region, bucket: data.bucket, prefix: String(data.prefix || "").replace(/^\/+|\/+$/g, ""), addressingStyle: "path", accessKey: data.accessKey, secretKey: data.secretKey ? sftp.sealCredential(data.secretKey) : (index >= 0 ? all[index].secretKey : ""), localPath: data.localPath || "", concurrency: Math.max(1, Math.min(16, Number(data.concurrency) || 4)), changedOnly: data.changedOnly !== false, createdAt: index >= 0 ? all[index].createdAt : new Date().toISOString(), updatedAt: new Date().toISOString() };
  if (!item.secretKey) return { success: false, message: "Unlock the credential vault before saving a secret key" };
  if (index >= 0) all[index] = item; else all.push(item); await writeAll(all); return { success: true, bucket: publicConfig(item) };
}
async function deleteBucket(id) { await writeAll((await readAll()).filter((x) => x.id !== id)); return { success: true }; }
async function raw(id) { const item = (await readAll()).find((x) => x.id === id); if (!item) throw new Error("S3 configuration not found"); const secretKey = sftp.openCredential(item.secretKey); if (!secretKey) throw new Error("Unlock the credential vault first"); return { ...item, secretKey }; }
function request(c, method, key = "", body = null, query = [], operation = method) {
  return new Promise((resolve, reject) => {
    const base = new URL(c.endpoint); const pathPrefix = base.pathname.replace(/\/+$/, "");
    // VNG vStorage and most S3-compatible services work with path-style URLs.
    // Keep the bucket separate from endpoint and never treat prefix as bucket.
    const pathName = c.addressingStyle === "virtual" ? `${pathPrefix}/${encodePath(key)}` : `${pathPrefix}/${encodePath(c.bucket)}/${encodePath(key)}`;
    if (c.addressingStyle === "virtual") base.hostname = `${c.bucket}.${base.hostname}`;
    const u = new URL(`${base.origin}${pathName || "/"}`);
    // Build the query once, before signing, and use the exact same bytes for
    // the outgoing URL. This preserves empty values such as location=.
    const pairs = Array.isArray(query) ? query.map(([k, v]) => [String(k), String(v ?? "")]) : String(query || "").replace(/^\?/, "").split("&").filter(Boolean).map((part) => { const i = part.indexOf("="); return [i < 0 ? part : part.slice(0, i), i < 0 ? "" : part.slice(i + 1)]; });
    pairs.sort((a, b) => encodeQuery(a[0]).localeCompare(encodeQuery(b[0])) || encodeQuery(a[1]).localeCompare(encodeQuery(b[1])));
    const canonicalQuery = pairs.map(([k, v]) => `${encodeQuery(k)}=${encodeQuery(v)}`).join("&"); u.search = canonicalQuery ? `?${canonicalQuery}` : "";
    const now = new Date(); const date = now.toISOString().replace(/[-:]/g, "").replace(/\.\d{3}Z$/, "Z"); const day = date.slice(0, 8); const payload = body ? (Buffer.isBuffer(body) ? body : Buffer.from(body)) : Buffer.alloc(0); const host = u.host.toLowerCase(); const canonicalURI = u.pathname || "/"; const payloadHash = sha256(payload); const headers = { host, "x-amz-content-sha256": payloadHash, "x-amz-date": date };
    const canonicalHeaders = `host:${host}\nx-amz-content-sha256:${payloadHash}\nx-amz-date:${date}\n`; const signed = "host;x-amz-content-sha256;x-amz-date"; const canonical = `${method}\n${canonicalURI}\n${canonicalQuery}\n${canonicalHeaders}\n${signed}\n${payloadHash}`; const scope = `${day}/${c.region}/s3/aws4_request`; const stringToSign = `AWS4-HMAC-SHA256\n${date}\n${scope}\n${sha256(canonical)}`; const signing = hmac(hmac(hmac(hmac(`AWS4${c.secretKey}`, day), c.region), "s3"), "aws4_request"); headers.authorization = `AWS4-HMAC-SHA256 Credential=${c.accessKey}/${scope}, SignedHeaders=${signed}, Signature=${crypto.createHmac("sha256", signing).update(stringToSign).digest("hex")}`;
    const debug = { method, canonicalURI, canonicalQueryString: canonicalQuery, signedHeaders: signed, hashedPayload: payloadHash, canonicalRequest: canonical, stringToSign, finalRequestUrl: u.toString(), endpoint: c.endpoint, hostname: u.hostname, bucket: c.bucket, region: c.region, forcePathStyle: c.addressingStyle !== "virtual", operation };
    log.info(`S3 SigV4 ${JSON.stringify(debug)}`);
    const req = (u.protocol === "http:" ? http : https).request(u, { method, headers }, (res) => { const chunks = []; res.on("data", (x) => chunks.push(x)); res.on("end", () => { const out = Buffer.concat(chunks); const text = out.toString("utf8"); const code = text.match(/<(?:Code|ErrorCode)>([^<]+)/)?.[1] || ""; const message = text.match(/<Message>([^<]+)/)?.[1] || res.statusMessage || text.slice(0, 500); const requestId = res.headers["x-amz-request-id"] || res.headers["x-vng-request-id"] || res.headers["x-request-id"] || text.match(/<(?:RequestId|RequestID)>([^<]+)/)?.[1] || ""; const meta = { ...debug, status: res.statusCode, responseHeaders: res.headers, body: text, code, message, requestId };
        if (res.statusCode >= 200 && res.statusCode < 300) resolve({ status: res.statusCode, body: out, meta }); else { const error = new Error(`S3 ${res.statusCode} ${code || "Error"}: ${message}`); error.s3 = meta; reject(error); }
      }); }); req.on("error", (error) => { error.s3 = { status: 0, body: error.message, code: "NETWORK_ERROR", message: error.message, endpoint: u.origin, requestUrl: u.toString(), region: c.region, bucket: c.bucket, operation }; reject(error); }); if (payload.length) req.write(payload); req.end();
  });
}
function formatError(error, operation, c) { const m = error.s3 || {}; const authCodes = ["SignatureDoesNotMatch", "InvalidAccessKeyId", "AuthorizationHeaderMalformed", "RequestTimeTooSkewed", "InvalidRequest"]; const permission = m.code === "AccessDenied" || m.code === "AllAccessDisabled"; const kind = m.status === 401 || authCodes.includes(m.code) ? "authentication/signature" : m.status === 403 && permission ? "permission/IAM" : m.status === 403 ? "authentication or permission" : m.status === 0 ? "network" : "request"; return { message: `${operation} failed (${kind}): HTTP ${m.status || "?"} ${m.code || ""} ${m.message || error.message}`, meta: { ...m, operation, region: c?.region, bucket: c?.bucket, forcePathStyle: c?.addressingStyle !== "virtual" } }; }
function xmlTags(xml, tag) { return [...xml.toString().matchAll(new RegExp(`<${tag}>([\\s\\S]*?)</${tag}>`, "g"))].map((m) => m[1]); }
async function list(c, prefix = "") { const out = []; let token = ""; do { const q = [["list-type", "2"], ["prefix", prefix]]; if (token) q.push(["continuation-token", token]); const xml = (await request(c, "GET", "", null, q, "ListObjectsV2")).body; const keys = xmlTags(xml, "Key"); const sizes = xmlTags(xml, "Size"); keys.forEach((key, i) => out.push({ key, size: Number(sizes[i] || 0) })); token = xmlTags(xml, "NextContinuationToken")[0] || ""; } while (token && !cancelled); return out; }
async function listObjects(id, prefix = "") { try { const c = await raw(id); return { success: true, items: await list(c, prefix || c.prefix) }; } catch (e) { const c = await readAll().then((x) => x.find((v) => v.id === id)); const info = formatError(e, "ListObjectsV2", c); log.err(`S3 ${JSON.stringify(info.meta)}`); return { success: false, message: info.message, details: info.meta }; } }
async function walk(dir, root = dir) { const out = []; for (const e of await fs.readdir(dir, { withFileTypes: true })) { const p = path.join(dir, e.name); if (e.isDirectory()) out.push(...await walk(p, root)); else if (e.isFile()) out.push({ local: p, relative: path.relative(root, p).split(path.sep).join("/") }); } return out; }
async function pool(items, concurrency, fn, progress) { let next = 0, done = 0; if (items.length) progress(0, items.length, items[0]); async function worker() { while (!cancelled) { const i = next++; if (i >= items.length) return; await fn(items[i]); progress(++done, items.length, items[i]); } } await Promise.all(Array.from({ length: Math.min(concurrency, Math.max(1, items.length)) }, worker)); }
async function test(id, progress = () => {}) {
  const c = await raw(id); const results = []; const testKey = `${c.prefix ? `${c.prefix}/` : ""}.shieldpress-connectivity-${Date.now()}.txt`;
  const steps = [
    ["HeadBucket", () => request(c, "HEAD", "", null, "", "HeadBucket")],
    ["GetBucketLocation", () => request(c, "GET", "", null, [["location", ""]], "GetBucketLocation")],
    ["ListObjectsV2", () => request(c, "GET", "", null, [["list-type", "2"], ["max-keys", "1"], ["prefix", c.prefix || ""]], "ListObjectsV2")],
    ["PutObject", () => request(c, "PUT", testKey, Buffer.from("shieldpress-connectivity-test"), "", "PutObject")],
    ["GetObject", () => request(c, "GET", testKey, null, "", "GetObject")],
    ["DeleteObject", () => request(c, "DELETE", testKey, null, "", "DeleteObject")],
  ];
  for (let index = 0; index < steps.length; index++) { const [operation, fn] = steps[index]; progress({ index, total: steps.length, operation, state: "running" }); try { const response = await fn(); const item = { operation, success: true, status: response.status, details: response.meta }; results.push(item); progress({ index, total: steps.length, operation, state: "success", status: response.status }); log.ok(`S3 ${operation} succeeded: ${c.endpoint}/${c.bucket} region=${c.region} pathStyle=true`); } catch (e) { const info = formatError(e, operation, c); const item = { operation, success: false, ...info, details: info.meta }; results.push(item); progress({ index, total: steps.length, operation, state: "error", status: info.meta.status, message: info.message }); log.err(`S3 ${JSON.stringify(info.meta)}`); } }
  const failed = results.filter((x) => !x.success); return { success: !failed.length, results, message: failed.length ? failed.map((x) => x.message).join("\n") : "All S3 checks passed" };
}
async function upload(id, opts = {}, progress = () => {}) { cancelled = false; const c = await raw(id); const root = opts.localPath || c.localPath; if (!root) throw new Error("Choose a local folder first"); const files = await walk(root); await pool(files, opts.concurrency || c.concurrency, async (f) => { const body = await fs.readFile(f.local); try { await request(c, "PUT", [c.prefix, f.relative].filter(Boolean).join("/"), body, "", "PutObject"); } catch (e) { const info = formatError(e, "PutObject", c); log.err(`S3 ${JSON.stringify(info.meta)}`); throw new Error(info.message); } }, progress); return { success: true, count: files.length }; }
async function uploadPaths(id, items, opts = {}, progress = () => {}) { cancelled = false; const c = await raw(id); const files = []; for (const item of items || []) { let stat; try { await fs.access(item, fs.constants.R_OK); stat = await fs.stat(item); } catch (e) { throw new Error(`Cannot read upload source "${item}" (${e.code || e.message}). Check WordPress/Laravel workspace permissions.`); } if (stat.isDirectory()) files.push(...await walk(item, path.dirname(item))); else files.push({ local: item, relative: path.basename(item) }); } await pool(files, opts.concurrency || c.concurrency, async (f) => { let body; try { body = await fs.readFile(f.local); } catch (e) { throw new Error(`Cannot read local file "${f.local}" (${e.code || e.message}). Check WordPress/Laravel workspace permissions.`); } try { await request(c, "PUT", [c.prefix, f.relative].filter(Boolean).join("/"), body, "", "PutObject"); } catch (e) { const info = formatError(e, "PutObject", c); log.err(`S3 ${JSON.stringify(info.meta)}`); throw new Error(info.message); } }, progress); return { success: true, count: files.length }; }
async function download(id, opts = {}, progress = () => {}) { cancelled = false; const c = await raw(id); const root = opts.localPath || c.localPath; if (!root) throw new Error("Choose a local folder first"); const files = (await list(c, c.prefix)).filter((x) => x.key && !x.key.endsWith("/")); await pool(files, opts.concurrency || c.concurrency, async (f) => { const body = (await request(c, "GET", f.key)).body; const rel = f.key.slice(c.prefix ? `${c.prefix}/`.length : 0); const target = path.join(root, ...rel.split("/")); await fs.ensureDir(path.dirname(target)); await fs.writeFile(target, body); }, progress); return { success: true, count: files.length }; }
async function downloadPrefix(id, prefix, localPath, opts = {}, progress = () => {}) { cancelled = false; const c = await raw(id); if (!localPath) throw new Error("Choose a local folder first"); const cleanPrefix = String(prefix || "").replace(/\/+$/, ""); const folderName = cleanPrefix.split("/").filter(Boolean).pop() || "download"; const files = (await list(c, prefix)).filter((x) => x.key && !x.key.endsWith("/")); await pool(files, opts.concurrency || c.concurrency, async (f) => { const rel = f.key.slice(cleanPrefix ? `${cleanPrefix}/`.length : 0); const target = path.join(localPath, folderName, ...rel.split("/")); await fs.ensureDir(path.dirname(target)); await fs.writeFile(target, (await request(c, "GET", f.key, null, [], "GetObject")).body); }, progress); return { success: true, count: files.length, folder: folderName }; }
async function downloadObject(id, key, localPath) { try { const c = await raw(id); const body = (await request(c, "GET", key, null, "", "GetObject")).body; await fs.ensureDir(path.dirname(localPath)); await fs.writeFile(localPath, body); return { success: true }; } catch (e) { const c = await readAll().then((x) => x.find((v) => v.id === id)); const info = formatError(e, "GetObject", c); log.err(`S3 ${JSON.stringify(info.meta)}`); return { success: false, message: info.message, details: info.meta }; } }
async function deleteObject(id, key) { try { const c = await raw(id); await request(c, "DELETE", key, null, "", "DeleteObject"); log.ok(`S3 object deleted: ${key}`); return { success: true }; } catch (e) { const c = await readAll().then((x) => x.find((v) => v.id === id)); const info = formatError(e, "DeleteObject", c); log.err(`S3 ${JSON.stringify(info.meta)}`); return { success: false, message: info.message, details: info.meta }; } }
function cancel() { cancelled = true; return { success: true }; }
module.exports = { getBuckets, saveBucket, deleteBucket, test, listObjects, upload, uploadPaths, download, downloadPrefix, downloadObject, deleteObject, cancel };
